### ISSUE TITLE
missing dma.h and poi.h

### ISSUE THREAD

**Issue by Gavin-Perry** [jostlowe/Pico-DMX#23]
Win11, Arduino 1.8.16 
Using Arduino-pico board manager with Generic RP2040 (WaveShare) 
Installed Pico-DMX from Library manager. No other package were loaded as dependencies.
When I try to compile I error on missing <dma.h> Can't find where to get this (or <pio.h> which will come up next)
Library looks great I can't wait to use it!

**Comment by khoih-prog** [comment]
Will be fixed by PR [**Add support to arduino-pico and mbed_nano core** #24](https://github.com/jostlowe/Pico-DMX/pull/24)
