### ISSUE TITLE
Wiring / setup diagram

### ISSUE THREAD

**Issue by LeonSutliffe** [jostlowe/Pico-DMX#37]
Hi, i know another user asked for this, but just some form of wiring or setup diagram for connecting the Pico to the rs485 modules would be really appreciated, even if its a drawing on the back of a napkin would go a long way to making the project more approachable. 

Thanks

Edit:   I have worked out the wiring for the project from the code, but if I had less technical experience with Arduino and raspberry pi (especially using max485 chips) I can see how it could be more complex to understand.

**Comment by jostlowe** [comment]
Duplicate of #36
