### ISSUE TITLE
DmxOutput.h void write not const

### ISSUE THREAD

**Issue by MarcusGarfunkel** [jostlowe/Pico-DMX#39]
Is there a reason write does not take a const uint8_t *universe? I'm just delving a little deeper into C++ itself and from my latest understanding, this would make more sense. I could be wrong, so wondering your thoughts.

Sincerely,
Marcus

**Comment by jostlowe** [comment]
Hi, Marcus!

You're absolutely right :) probably a little slip up that was made in the infancy of this library that was never caught.
