### ISSUE TITLE
which pins are best used for simultaneous input and output 

### ISSUE THREAD

**Issue by stephanschulz** [jostlowe/Pico-DMX#41]
I am hoping to use the rpi pico to receive dmx data and send it out again. I am using a rs485 transceiver LTC2851.
I have not been able to find any info using GPIO 0 as input and GPIO as output would work. I think they are both on the same `pio`?

Would this work?
```
  dmxInput.begin(0, START_CHANNEL, NUM_CHANNELS);
  dmxOutput.begin(1, pio1);
```

**Comment by joelschoene** [comment]
Have a look on https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf page 309. There you can see, that all state machines are muxed on all GPIOs. So you can use the pin, you want to.
