### ISSUE TITLE
RDM Compatibility?

### ISSUE THREAD

**Issue by LeonSutliffe** [jostlowe/Pico-DMX#52]
Hi! sorry for a couple things posted in a row, but  i thought id put in a feature request.  what would be great as something to make this library on par, if not better than its arduino counterparts would be the addition of RDM, while it definitely isnt necessary, it would make an already great library even better.

thanks,
Leon

**Comment by jostlowe** [comment]
No worries :) we're here to help.

Please see #43 

TL;DR: It is technically possible, but not planned at the moment
